/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8Qbd3vNo5NC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"

export function testthree() {
  return (
    (<div className="flex flex-col h-screen bg-gray-100 dark:bg-gray-950">
      <header className="bg-white dark:bg-gray-900 shadow-sm py-4 px-6">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-50">Todo List</h1>
      </header>
      <main className="flex-1 py-8 px-6">
        <div className="max-w-md mx-auto space-y-4">
          <form className="grid grid-cols-[auto_1fr] items-center gap-4">
            <label className="font-medium text-gray-700 dark:text-gray-400" htmlFor="time">
              Time
            </label>
            <input
              className="bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-md px-3 py-2 text-gray-900 dark:text-gray-50 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
              id="time"
              type="time" />
            <label className="font-medium text-gray-700 dark:text-gray-400" htmlFor="title">
              Title
            </label>
            <input
              className="bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-md px-3 py-2 text-gray-900 dark:text-gray-50 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
              id="title"
              placeholder="Enter a title"
              type="text" />
            <label
              className="font-medium text-gray-700 dark:text-gray-400"
              htmlFor="description">
              Description
            </label>
            <textarea
              className="bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-md px-3 py-2 text-gray-900 dark:text-gray-50 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
              id="description"
              placeholder="Enter a description"
              rows={3} />
            <Button className="col-span-2 justify-self-end" type="submit">
              Add Todo
            </Button>
          </form>
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-sm">
            <ul className="divide-y divide-gray-200 dark:divide-gray-800">
              <li className="flex items-center justify-between px-4 py-3">
                <div className="flex items-center space-x-3">
                  <Checkbox id="todo1" />
                  <div>
                    <div className="font-medium text-gray-900 dark:text-gray-50">Finish project proposal</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">Due by 10:00 AM</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">
                      Prepare the project proposal for the client meeting.
                    </div>
                  </div>
                </div>
                <Button
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  size="icon"
                  variant="ghost">
                  <TrashIcon className="w-5 h-5" />
                  <span className="sr-only">Delete</span>
                </Button>
              </li>
              <li className="flex items-center justify-between px-4 py-3">
                <div className="flex items-center space-x-3">
                  <Checkbox defaultChecked id="todo2" />
                  <div className="line-through text-gray-400 dark:text-gray-600">
                    <div className="font-medium">Review and approve design mockups</div>
                    <div className="text-sm">Due by 3:00 PM</div>
                    <div className="text-sm">Review the design mockups and provide feedback to the design team.</div>
                  </div>
                </div>
                <Button
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  size="icon"
                  variant="ghost">
                  <TrashIcon className="w-5 h-5" />
                  <span className="sr-only">Delete</span>
                </Button>
              </li>
              <li className="flex items-center justify-between px-4 py-3">
                <div className="flex items-center space-x-3">
                  <Checkbox id="todo3" />
                  <div>
                    <div className="font-medium text-gray-900 dark:text-gray-50">Attend team meeting</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">Due by 4:30 PM</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">
                      Participate in the weekly team meeting to discuss progress and upcoming tasks.
                    </div>
                  </div>
                </div>
                <Button
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  size="icon"
                  variant="ghost">
                  <TrashIcon className="w-5 h-5" />
                  <span className="sr-only">Delete</span>
                </Button>
              </li>
            </ul>
          </div>
        </div>
      </main>
    </div>)
  );
}

function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}
