/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Fs7CYd5N51s
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"

export function testtwo() {
  return (
    (<div className="flex flex-col h-screen">
      <header className="bg-gray-900 text-white py-4 px-6">
        <h1 className="text-2xl font-bold">Todo List</h1>
      </header>
      <main className="flex-1 p-6">
        <div className="mb-6">
          <h2 className="text-lg font-bold mb-2">Add New Todo</h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <Input placeholder="Time" type="text" />
            <Input placeholder="Title" type="text" />
            <Input placeholder="Description" type="text" />
          </div>
          <Button className="mt-4">Add Todo</Button>
        </div>
        <div className="mb-6">
          <h2 className="text-lg font-bold mb-2">Todos</h2>
          <div className="flex items-center mb-4">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button className="mr-4" variant="outline">
                  Show All
                  <ChevronDownIcon className="ml-2 w-4 h-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem>Show All</DropdownMenuItem>
                <DropdownMenuItem>Show Completed</DropdownMenuItem>
                <DropdownMenuItem>Show Incomplete</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
          <div className="grid gap-4" />
        </div>
      </main>
    </div>)
  );
}

function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}
